// soldier-list
export const FETCH_LIST_START = "FETCH_LIST_START";
export const FETCH_LIST_FAIL = "FETCH_LIST_FAIL";
export const FETCH_LIST_SUCCESS_APPEND= "FETCH_LIST_SUCCESS_APPEND";
export const FETCH_LIST_SUCCESS_REPLACE = "FETCH_LIST_SUCCESS_REPLACE";
export const UPDATE_LIST_QUERY = "UPDATE_LIST_QUERY";
export const CLEAN_LIST_LIST = "CLEAN_LIST_LIST";
// create-soldier
export const CREATE_SOLDIER_START = "CREATE_SOLDIER_START";
export const CREATE_SOLDIER_FAIL = "CREATE_SOLDIER_FAIL";
export const CREATE_SOLDIER_SUCCESS = "CREATE_SOLDIER_SUCCESS";
// edit-soldier
export const EDIT_SOLDIER_START = "EDIT_SOLDIER_START";
export const EDIT_SOLDIER_FAIL = "EDIT_SOLDIER_FAIL";
export const EDIT_SOLDIER_SUCCESS = "EDIT_SOLDIER_SUCCESS";
// delete-soldier
export const DEL_SOLDIER_START = "DEL_SOLDIER_START";
export const DEL_SOLDIER_FAIL = "DEL_SOLDIER_FAIL";
export const DEL_SOLDIER_SUCCESS = "DEL_SOLDIER_SUCCESS";
// get-all-sups
export const GET_SUP_START = "GET_SUP_START";
export const GET_SUP_FAIL = "GET_SUP_FAIL";
export const GET_SUP_SUCCESS = "GET_SUP_SUCCESS";